ERROR - 2022-10-10 00:00:49 --> mysqli_sql_exception: Table 'spm.usuario' doesn't exist in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
#6 C:\xampp\htdocs\tesis\app\Controllers\Postulante.php(158): CodeIgniter\BaseModel->find('222')
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
#9 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-10-10 00:00:49 --> Table 'spm.usuario' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `usuario`
WHERE `usuario`.`ID_USUARIO` = \'222\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `usuario`
WHERE `usuario`.`ID_USUARIO` = \'222\'')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `usuario`
WHERE `usuario`.`ID_USUARIO` = \'222\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `usuario`.`ID_USUARIO` = :usuario.ID_USUARIO:', [...], false)
 5 SYSTEMPATH\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
 7 APPPATH\Controllers\Postulante.php(158): CodeIgniter\BaseModel->find('222')
 8 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
 9 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 00:01:50 --> Class 'App\Controllers\PostulanteModel' not found
in APPPATH\Controllers\Postulante.php on line 32.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->postulantes()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 00:03:54 --> Class 'App\Controllers\PostulanteModel' not found
in APPPATH\Controllers\Postulante.php on line 123.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 00:04:09 --> Undefined variable: postulanteModel
in APPPATH\Controllers\Postulante.php on line 132.
 1 APPPATH\Controllers\Postulante.php(132): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: postulanteModel', 'APPPATH\\Controllers\\Postulante.php', 132, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 00:06:00 --> Undefined variable: postulanteModel
in APPPATH\Controllers\Postulante.php on line 128.
 1 APPPATH\Controllers\Postulante.php(128): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: postulanteModel', 'APPPATH\\Controllers\\Postulante.php', 128, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 00:06:16 --> Undefined index: ID_CARRERA
in APPPATH\Controllers\Postulante.php on line 131.
 1 APPPATH\Controllers\Postulante.php(131): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: ID_CARRERA', 'APPPATH\\Controllers\\Postulante.php', 131, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 00:06:35 --> Undefined variable: usuario
in APPPATH\Controllers\Postulante.php on line 149.
 1 APPPATH\Controllers\Postulante.php(149): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: usuario', 'APPPATH\\Controllers\\Postulante.php', 149, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 00:07:05 --> Undefined index: NOMBRE_USUARIO
in APPPATH\Views\admin\postulaciones\individual.php on line 52.
 1 APPPATH\Views\admin\postulaciones\individual.php(52): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: NOMBRE_USUARIO', 'APPPATH\\Views\\admin\\postulaciones\\individual.php', 52, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\postulaciones\\individual.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/postulaciones/individual', [], true)
 5 APPPATH\Controllers\Postulante.php(155): view('admin/postulaciones/individual', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 00:07:53 --> Undefined index: ID_POSTULANTE
in APPPATH\Views\admin\postulaciones\individual.php on line 77.
 1 APPPATH\Views\admin\postulaciones\individual.php(77): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: ID_POSTULANTE', 'APPPATH\\Views\\admin\\postulaciones\\individual.php', 77, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\postulaciones\\individual.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/postulaciones/individual', [], true)
 5 APPPATH\Controllers\Postulante.php(155): view('admin/postulaciones/individual', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 00:08:24 --> Undefined index: EMAIL_POSTULANTE
in APPPATH\Views\admin\postulaciones\individual.php on line 98.
 1 APPPATH\Views\admin\postulaciones\individual.php(98): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: EMAIL_POSTULANTE', 'APPPATH\\Views\\admin\\postulaciones\\individual.php', 98, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\postulaciones\\individual.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/postulaciones/individual', [], true)
 5 APPPATH\Controllers\Postulante.php(155): view('admin/postulaciones/individual', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Postulante->registro('58')
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Postulante))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 09:29:12 --> Undefined index: preguntas
in APPPATH\Controllers\Convocatoria.php on line 139.
 1 APPPATH\Controllers\Convocatoria.php(139): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: preguntas', 'APPPATH\\Controllers\\Convocatoria.php', 139, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->creada()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 11:36:49 --> Undefined index: ID_DET_USER
in APPPATH\Controllers\AuthSPM.php on line 53.
 1 APPPATH\Controllers\AuthSPM.php(53): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: ID_DET_USER', 'APPPATH\\Controllers\\AuthSPM.php', 53, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 12:22:29 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\formularios\vista.php on line 112.
 1 APPPATH\Views\admin\formularios\vista.php(112): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\formularios\\vista.php', 112, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\formularios\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/formularios/vista', [], true)
 5 APPPATH\Controllers\Formulario.php(45): view('admin/formularios/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 12:57:19 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\formularios\vista.php on line 116.
 1 APPPATH\Views\admin\formularios\vista.php(116): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\formularios\\vista.php', 116, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\formularios\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/formularios/vista', [], true)
 5 APPPATH\Controllers\Formulario.php(45): view('admin/formularios/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 13:19:15 --> Illegal string offset 'ID_PREGUNTA'
in APPPATH\Views\admin\formularios\vista.php on line 115.
 1 APPPATH\Views\admin\formularios\vista.php(115): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Illegal string offset \'ID_PREGUNTA\'', 'APPPATH\\Views\\admin\\formularios\\vista.php', 115, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\formularios\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/formularios/vista', [], true)
 5 APPPATH\Controllers\Formulario.php(55): view('admin/formularios/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 13:46:21 --> Class 'App\Controllers\InputModel' not found
in APPPATH\Controllers\Formulario.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 13:46:43 --> Class 'App\Controllers\CheckBoxModel' not found
in APPPATH\Controllers\Formulario.php on line 25.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 13:47:06 --> Class 'App\Models\CheckBoxModel' not found
in APPPATH\Controllers\Formulario.php on line 28.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 13:54:52 --> Illegal string offset 'ID_PREGUNTA'
in APPPATH\Views\admin\formularios\vista.php on line 115.
 1 APPPATH\Views\admin\formularios\vista.php(115): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Illegal string offset \'ID_PREGUNTA\'', 'APPPATH\\Views\\admin\\formularios\\vista.php', 115, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\formularios\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/formularios/vista', [], true)
 5 APPPATH\Controllers\Formulario.php(80): view('admin/formularios/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 14:07:32 --> array_push() expects parameter 1 to be array, string given
in APPPATH\Controllers\Formulario.php on line 57.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'array_push() expects parameter 1 to be array, string given', 'APPPATH\\Controllers\\Formulario.php', 57, [...])
 2 APPPATH\Controllers\Formulario.php(57): array_push('1')
 3 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 15:08:23 --> Illegal string offset 'ID_PREGUNTA'
in APPPATH\Views\admin\formularios\vista.php on line 115.
 1 APPPATH\Views\admin\formularios\vista.php(115): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Illegal string offset \'ID_PREGUNTA\'', 'APPPATH\\Views\\admin\\formularios\\vista.php', 115, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\formularios\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/formularios/vista', [], true)
 5 APPPATH\Controllers\Formulario.php(90): view('admin/formularios/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 15:17:12 --> Undefined variable: array_preguntas
in APPPATH\Controllers\Formulario.php on line 82.
 1 APPPATH\Controllers\Formulario.php(82): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: array_preguntas', 'APPPATH\\Controllers\\Formulario.php', 82, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 18:01:17 --> Class 'App\Controllers\PreguntaMultipleModel' not found
in APPPATH\Controllers\Formulario.php on line 27.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 18:01:40 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 300.
 1 APPPATH\Views\admin\convocatorias\vista.php(300): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 300, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(106): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 18:07:44 --> Class 'App\Controllers\InputModel' not found
in APPPATH\Controllers\Convocatoria.php on line 39.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 18:08:02 --> Class 'App\Controllers\InputModel' not found
in APPPATH\Controllers\Convocatoria.php on line 39.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 18:08:34 --> Undefined variable: preguntas
in APPPATH\Controllers\Convocatoria.php on line 131.
 1 APPPATH\Controllers\Convocatoria.php(131): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: preguntas', 'APPPATH\\Controllers\\Convocatoria.php', 131, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 18:08:47 --> Undefined variable: preguntas
in APPPATH\Views\admin\convocatorias\vista.php on line 298.
 1 APPPATH\Views\admin\convocatorias\vista.php(298): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: preguntas', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 298, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(133): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 18:09:42 --> Undefined variable: preguntas
in APPPATH\Views\admin\convocatorias\vista.php on line 298.
 1 APPPATH\Views\admin\convocatorias\vista.php(298): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: preguntas', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 298, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(135): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 18:11:32 --> Undefined variable: preguntas
in APPPATH\Views\admin\convocatorias\vista.php on line 298.
 1 APPPATH\Views\admin\convocatorias\vista.php(298): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: preguntas', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 298, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(143): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:12:42 --> Undefined variable: input_tipo
in APPPATH\Controllers\Convocatoria.php on line 119.
 1 APPPATH\Controllers\Convocatoria.php(119): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: input_tipo', 'APPPATH\\Controllers\\Convocatoria.php', 119, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:13:03 --> Undefined variable: input_tipo
in APPPATH\Controllers\Convocatoria.php on line 119.
 1 APPPATH\Controllers\Convocatoria.php(119): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: input_tipo', 'APPPATH\\Controllers\\Convocatoria.php', 119, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:13:34 --> Undefined variable: input_tipo
in APPPATH\Controllers\Convocatoria.php on line 124.
 1 APPPATH\Controllers\Convocatoria.php(124): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: input_tipo', 'APPPATH\\Controllers\\Convocatoria.php', 124, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:14:06 --> Undefined variable: preguntas
in APPPATH\Views\admin\convocatorias\vista.php on line 298.
 1 APPPATH\Views\admin\convocatorias\vista.php(298): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: preguntas', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 298, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(188): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:14:15 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 300.
 1 APPPATH\Views\admin\convocatorias\vista.php(300): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 300, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(188): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:14:57 --> Undefined index: TITULO
in APPPATH\Views\admin\convocatorias\vista.php on line 300.
 1 APPPATH\Views\admin\convocatorias\vista.php(300): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 300, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(188): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:15:14 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 300.
 1 APPPATH\Views\admin\convocatorias\vista.php(300): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 300, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(188): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:15:29 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 300.
 1 APPPATH\Views\admin\convocatorias\vista.php(300): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 300, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(190): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:16:38 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 300.
 1 APPPATH\Views\admin\convocatorias\vista.php(300): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 300, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(190): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:17:25 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 300.
 1 APPPATH\Views\admin\convocatorias\vista.php(300): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 300, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(191): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:17:39 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 300.
 1 APPPATH\Views\admin\convocatorias\vista.php(300): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 300, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(193): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:19:00 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 304.
 1 APPPATH\Views\admin\convocatorias\vista.php(304): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 304, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(193): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:21:12 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 303.
 1 APPPATH\Views\admin\convocatorias\vista.php(303): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 303, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(193): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:21:32 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 303.
 1 APPPATH\Views\admin\convocatorias\vista.php(303): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 303, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(179): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:22:16 --> Undefined index: TITULO_PREGUNTA
in APPPATH\Views\admin\convocatorias\vista.php on line 303.
 1 APPPATH\Views\admin\convocatorias\vista.php(303): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: TITULO_PREGUNTA', 'APPPATH\\Views\\admin\\convocatorias\\vista.php', 303, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\convocatorias\\vista.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1137): CodeIgniter\View\View->render('admin/convocatorias/vista', [], true)
 5 APPPATH\Controllers\Convocatoria.php(195): view('admin/convocatorias/vista', [...])
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Convocatoria->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Convocatoria))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:23:37 --> Undefined variable: dropdowns
in APPPATH\Controllers\Formulario.php on line 110.
 1 APPPATH\Controllers\Formulario.php(110): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: dropdowns', 'APPPATH\\Controllers\\Formulario.php', 110, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:24:47 --> Undefined variable: preguntasModel
in APPPATH\Controllers\Formulario.php on line 61.
 1 APPPATH\Controllers\Formulario.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: preguntasModel', 'APPPATH\\Controllers\\Formulario.php', 61, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:24:55 --> Class 'App\Controllers\PreguntaModel' not found
in APPPATH\Controllers\Formulario.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:25:05 --> Undefined variable: preguntasModel
in APPPATH\Controllers\Formulario.php on line 61.
 1 APPPATH\Controllers\Formulario.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: preguntasModel', 'APPPATH\\Controllers\\Formulario.php', 61, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:25:33 --> Undefined variable: pregunta
in APPPATH\Controllers\Formulario.php on line 124.
 1 APPPATH\Controllers\Formulario.php(124): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: pregunta', 'APPPATH\\Controllers\\Formulario.php', 124, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Formulario->formulario()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formulario))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-10 21:35:10 --> Undefined variable: postulante
in APPPATH\Controllers\Estudiante.php on line 253.
 1 APPPATH\Controllers\Estudiante.php(253): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: postulante', 'APPPATH\\Controllers\\Estudiante.php', 253, [...])
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Estudiante->historial()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Estudiante))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-10 21:49:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'TOPHER'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'TOPHER', '123', 'spm', 3306, '', 0)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '6169')
#6 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('6169')
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#9 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '6169')
#5 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('6169')
#6 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-10-10 21:49:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user`.`ID_USER` = :user.ID_USER:', [...], false)
 3 SYSTEMPATH\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '6169')
 5 APPPATH\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('6169')
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-10 21:50:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'TOPHER'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'TOPHER', '123', 'spm', 3306, '', 0)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '6169')
#6 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('6169')
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#9 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '6169')
#5 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('6169')
#6 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-10-10 21:50:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user`.`ID_USER` = :user.ID_USER:', [...], false)
 3 SYSTEMPATH\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '6169')
 5 APPPATH\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('6169')
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-10 21:50:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'TOPHER'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'TOPHER', '123', 'spm', 3306, '', 0)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '6169')
#6 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('6169')
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#9 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '6169')
#5 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('6169')
#6 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-10-10 21:50:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user`.`ID_USER` = :user.ID_USER:', [...], false)
 3 SYSTEMPATH\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '6169')
 5 APPPATH\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('6169')
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-10 21:50:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'TOPHER'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'TOPHER', '123', 'spm', 3306, '', 0)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
#6 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#9 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
#5 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
#6 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-10-10 21:50:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user`.`ID_USER` = :user.ID_USER:', [...], false)
 3 SYSTEMPATH\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
 5 APPPATH\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-10 21:50:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'TOPHER'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'TOPHER', '123', 'spm', 3306, '', 0)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
#6 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#9 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
#5 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
#6 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-10-10 21:50:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user`.`ID_USER` = :user.ID_USER:', [...], false)
 3 SYSTEMPATH\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
 5 APPPATH\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-10 21:58:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'TOPHER'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'TOPHER', '123', 'spm', 3306, '', 0)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
#6 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#9 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
#5 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
#6 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-10-10 21:58:09 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user`.`ID_USER` = :user.ID_USER:', [...], false)
 3 SYSTEMPATH\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
 5 APPPATH\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-10 21:59:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'TOPHER'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'TOPHER', '123', 'spm', 3306, '', 0)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
#6 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#9 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\tesis\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tesis\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tesis\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tesis\system\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tesis\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
#5 C:\xampp\htdocs\tesis\app\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
#6 C:\xampp\htdocs\tesis\system\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
#7 C:\xampp\htdocs\tesis\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
#8 C:\xampp\htdocs\tesis\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tesis\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-10-10 21:59:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `user`.`ID_USER` = :user.ID_USER:', [...], false)
 3 SYSTEMPATH\Model.php(181): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(523): CodeIgniter\Model->doFind(true, '222')
 5 APPPATH\Controllers\AuthSPM.php(31): CodeIgniter\BaseModel->find('222')
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\AuthSPM->validador()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthSPM))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
